export const UpcomingMoviesActionTypes = {
    FETCH_UPCOMING_MOVIES_PENDING: 'FETCH_UPCOMING_MOVIES_PENDING',
    FETCH_UPCOMING_MOVIES_SUCCESS: 'FETCH_UPCOMING_MOVIES_SUCCESS',
    FETCH_UPCOMING_MOVIES_ERROR: 'FETCH_UPCOMING_MOVIES_ERROR'
}