export const PopularMoviesActionTypes = {
    FETCH_POPULAR_MOVIES_PENDING: 'FETCH_POPULAR_MOVIES_PENDING',
    FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_ERROR: 'FETCH_POPULAR_MOVIES_ERROR'
}